using AutoMapper;
using Microsoft.EntityFrameworkCore;
using RF.WebApi.Api.Apis.Authentication;
using RF.WebApi.Api.Application.DTOs.BuyingBill;
using RF.WebApi.Api.Domain.Common;
using RF.WebApi.Api.Domain.Exceptions;
using RF.WebApi.Api.Domain.Interfaces;
using RF.WebApi.Api.Infrastructure.Data.Tables;
using RF.WebApi.Infrastructure.Data.DataBase;


namespace RF.WebApi.Api.Infrastructure.Services
{
    public class BuyingBillService : IBuyingBillService
    {
        private readonly RFDBContext _context;
        private readonly IMapper _mapper;
        private readonly IBusinessYearService _businessYearService;
        private readonly IPdfService _pdfService;

        public BuyingBillService(RFDBContext context, IMapper mapper, IBusinessYearService businessYearService, IPdfService pdfService)
        {
            _context = context;
            _mapper = mapper;
            _businessYearService = businessYearService;
            _pdfService = pdfService;
        }

        public async Task<ServiceResponse<int>> CreateBuyingBill(CreateBuyingBillDto dto)
        {
            return await ServiceResponse<int>.Execute(async err =>
            {
                var accountId = Token.AccountId;

                var bill = _mapper.Map<BuyingBill>(dto);
                bill.AccountId = accountId;

                bool isAutogeneratedNeeded = string.IsNullOrWhiteSpace(bill.BillNo);
                if (isAutogeneratedNeeded)
                {
                    bill.BillNo = "TEMP_BILL_NO";
                }

                _context.BuyingBills.Add(bill);
                
                foreach (var stock in bill.Stocks)
                {
                    stock.Date = bill.Date;
                }

                foreach (var payment in bill.Payments)
                {
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();

                if (bill.BillNo == "TEMP_BILL_NO")
                {
                    var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == accountId);
                    string initials = "ABC";
                    if (account != null && !string.IsNullOrWhiteSpace(account.ProfileName))
                    {
                        var words = account.ProfileName.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                        if (words.Length > 0)
                        {
                            initials = string.Join("", words.Select(w => w[0])).ToUpper();
                        }
                    }

                    string year = bill.Date.HasValue ? bill.Date.Value.Year.ToString() : DateTime.Now.Year.ToString();
                    bill.BillNo = $"{initials}{year}BB{bill.Id}";
                    await _context.SaveChangesAsync();
                }

                // Save the expenses as BusinessExpence records linked to this bill
                await SyncBillExpencesToBusinessExpences(bill.Id!.Value, accountId, bill.Date!.Value, dto.Expences
                    .Select(e => new BuyingBillExpenceSyncDto
                    {
                        Id = null,
                        ExpenceType = e.ExpenceType,
                        TotalAmount = e.TotalAmount,
                        Payments = e.Payments
                    }).ToList());

                return bill.Id ?? default;
            });
        }

        public Task<ServiceResponse<BuyingBillDto>> GetBuyingBillById(int id)
        {
            return ServiceResponse<BuyingBillDto>.Execute(async err =>
            {
                var bill = await _context.BuyingBills
                    .Include(b => b.Stocks)
                        .ThenInclude(s => s.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(BuyingBillMessages.NotFound);
                    return default;
                }

                var dto = _mapper.Map<BuyingBillDto>(bill);

                // Load linked BusinessExpences for display in the form
                var linkedExpences = await _context.BusinessExpences
                    .Include(e => e.Payments)
                    .Where(e => e.BuyingBillId == id && e.AccountId == Token.AccountId)
                    .AsNoTracking()
                    .ToListAsync();

                dto.Expences = linkedExpences.Select(e => new BuyingBillExpenceDto
                {
                    Id = e.Id ?? 0,
                    ExpenceType = e.ExpenceType ?? string.Empty,
                    TotalAmount = e.TotalAmount ?? 0,
                    Payments = e.Payments.Select(p => new BuyingBillExpencePaymentDto
                    {
                        Id = p.Id,
                        Amount = p.Amount ?? 0,
                        PaymentAccountId = p.PaymentAccountId ?? 0
                    }).ToList()
                }).ToList();

                return dto;
            });
        }

        public Task<ServiceResponse<bool>> UpdateBuyingBill(UpdateBuyingBillDto dto)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.BuyingBills
                    .Include(b => b.Stocks)
                        .ThenInclude(s => s.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == dto.Id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(BuyingBillMessages.NotFound);
                    return false;
                }

                // Sync scalar properties (Stocks, Payments are synced; Expences go to BusinessExpence)
                _mapper.Map(dto, bill);

                _context.SyncCollection(bill.Stocks, dto.Stocks, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);
                _context.SyncCollection(bill.Payments, dto.Payments, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);
 
                foreach (var stock in bill.Stocks)
                {
                    stock.Date = bill.Date;
                }

                foreach (var payment in bill.Payments)
                {
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();

                // Sync the buying-bill expenses into BusinessExpence
                var expenceSyncDtos = dto.Expences.Select(e => new BuyingBillExpenceSyncDto
                {
                    Id = e.Id,
                    ExpenceType = e.ExpenceType,
                    TotalAmount = e.TotalAmount,
                    Payments = e.Payments
                }).ToList();

                await SyncBillExpencesToBusinessExpences(dto.Id, Token.AccountId, bill.Date!.Value, expenceSyncDtos);

                return true;
            });
        }

        public Task<ServiceResponse<bool>> DeleteBuyingBill(int id)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.BuyingBills
                    .Include(b => b.Stocks)
                        .ThenInclude(s => s.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(BuyingBillMessages.NotFound);
                    return false;
                }

                // Delete linked BusinessExpences (and their payments via cascade)
                var linkedExpences = await _context.BusinessExpences
                    .Include(e => e.Payments)
                    .Where(e => e.BuyingBillId == id && e.AccountId == Token.AccountId)
                    .ToListAsync();

                foreach (var exp in linkedExpences)
                {
                    _context.BusinessExpencePayments.RemoveRange(exp.Payments);
                    _context.BusinessExpences.Remove(exp);
                }

                _context.Stocks.RemoveRange(bill.Stocks);
                _context.BuyingBillPayments.RemoveRange(bill.Payments);
                _context.BuyingBills.Remove(bill);

                await _context.SaveChangesAsync();

                return true;
            });
        }

        public Task<ServiceResponse<List<BuyingBillListDto>>> GetAllBuyingBills()
        {
            return ServiceResponse<List<BuyingBillListDto>>.Execute(async err =>
            {
                var accountId = Token.AccountId;

                var dateRangeResponse = await _businessYearService.GetSelectedBusinessYearDates();
                if (!dateRangeResponse.Success)
                {
                    err.SetErrors(dateRangeResponse);
                    return default;
                }

                var (startDate, endDate) = dateRangeResponse.Data;

                var bills = await _context.BuyingBills
                    .Include(b => b.Agency)
                    .Include(b => b.Stocks)
                    .Include(b => b.Payments)
                    .Include(b => b.Expences)
                    .Where(b => b.AccountId == accountId && b.Date >= startDate && b.Date <= endDate)
                    .OrderByDescending(b => b.Date)
                    .AsNoTracking()
                    .ToListAsync();

                return _mapper.Map<List<BuyingBillListDto>>(bills);
            });
        }

        public Task<ServiceResponse<List<BuyingBillListDto>>> GetAllBuyingBillsByAgencyId(int agencyId)
        {
            return ServiceResponse<List<BuyingBillListDto>>.Execute(async err =>
            {
                var accountId = Token.AccountId;

                var dateRangeResponse = await _businessYearService.GetSelectedBusinessYearDates();
                if (!dateRangeResponse.Success)
                {
                    err.SetErrors(dateRangeResponse);
                    return default;
                }

                var (startDate, endDate) = dateRangeResponse.Data;

                var bills = await _context.BuyingBills
                    .Include(b => b.Agency)
                    .Include(b => b.Stocks)
                    .Include(b => b.Payments)
                    .Include(b => b.Expences)
                    .Where(b => b.AccountId == accountId && b.AgencyId == agencyId && b.Date >= startDate && b.Date <= endDate)
                    .OrderByDescending(b => b.Date)
                    .AsNoTracking()
                    .ToListAsync();

                return _mapper.Map<List<BuyingBillListDto>>(bills);
            });
        }

        public Task<ServiceResponse<List<string>>> GetExpenceTypeSuggestions()
        {
            return ServiceResponse<List<string>>.Execute(async err =>
            {
                var accountId = Token.AccountId;

                // Pull suggestions from BusinessExpences linked to buying bills
                var suggestions = await _context.BusinessExpences
                    .Where(e => e.AccountId == accountId && e.BuyingBillId != null && !string.IsNullOrWhiteSpace(e.ExpenceType))
                    .Select(e => e.ExpenceType!)
                    .GroupBy(x => x.Trim())
                    .OrderByDescending(g => g.Count())
                    .Select(g => g.Key)
                    .ToListAsync();

                return suggestions;
            });
        }

        public Task<ServiceResponse<byte[]>> GenerateInvoicePdf(int id)
        {
            return ServiceResponse<byte[]>.Execute(async err =>
            {
                var bill = await _context.BuyingBills
                    .Include(b => b.Agency)
                    .Include(b => b.Stocks)
                        .ThenInclude(s => s.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(BuyingBillMessages.NotFound);
                    return default;
                }

                var expences = await _context.BusinessExpences
                    .Include(e => e.Payments)
                    .Where(e => e.BuyingBillId == id && e.AccountId == Token.AccountId)
                    .AsNoTracking()
                    .ToListAsync();

                var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == Token.AccountId);
                if (account == null)
                {
                    err.AddError("Account not found");
                    return default;
                }

                return await _pdfService.GenerateBuyingBillPdf(bill, account, expences);
            });
        }

        public Task<ServiceResponse<bool>> UpdatePayments(int billId, List<BuyingBillPaymentDto> payments)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.BuyingBills
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == billId && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(BuyingBillMessages.NotFound);
                    return false;
                }

                _context.SyncCollection(bill.Payments, payments, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);

                foreach (var payment in bill.Payments)
                {
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();
                return true;
            });
        }

        // ---------------------------------------------------------------------------
        // Private helpers
        // ---------------------------------------------------------------------------

        /// <summary>
        /// Syncs the expense entries from a buying bill into the BusinessExpence table.
        /// Existing linked expenses are updated/removed; new ones are added.
        /// </summary>
        private async Task SyncBillExpencesToBusinessExpences(
            int billId, int accountId, DateOnly billDate,
            List<BuyingBillExpenceSyncDto> incomingExpences)
        {
            // Load all existing BusinessExpences linked to this bill
            var existing = await _context.BusinessExpences
                .Include(e => e.Payments)
                .Where(e => e.BuyingBillId == billId && e.AccountId == accountId)
                .ToListAsync();

            var incomingIds = incomingExpences
                .Where(e => e.Id.HasValue)
                .Select(e => e.Id!.Value)
                .ToHashSet();

            // Remove expenses that are no longer in the list
            foreach (var exp in existing.Where(e => !incomingIds.Contains(e.Id!.Value)))
            {
                _context.BusinessExpencePayments.RemoveRange(exp.Payments);
                _context.BusinessExpences.Remove(exp);
            }

            foreach (var incoming in incomingExpences)
            {
                if (incoming.Id.HasValue && incoming.Id.Value > 0)
                {
                    // Update existing
                    var exp = existing.FirstOrDefault(e => e.Id == incoming.Id.Value);
                    if (exp != null)
                    {
                        exp.ExpenceType = incoming.ExpenceType;
                        exp.TotalAmount = incoming.TotalAmount;
                        exp.Date = billDate;

                        // Sync payments
                        var incomingPayments = incoming.Payments.Select(p => new BusinessExpencePayment
                        {
                            Id = p.Id ?? 0,
                            Amount = p.Amount,
                            PaymentAccountId = p.PaymentAccountId,
                            BusinessExpenceId = exp.Id ?? 0,
                            Date = p.Date ?? billDate
                        }).ToList();

                        _context.SyncCollection(exp.Payments, incomingPayments, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);
                    }
                }
                else
                {
                    // Create new
                    var newExp = new BusinessExpence
                    {
                        AccountId = accountId,
                        BuyingBillId = billId,
                        ExpenceType = incoming.ExpenceType,
                        TotalAmount = incoming.TotalAmount,
                        Date = billDate
                    };
                    
                    foreach (var p in incoming.Payments)
                    {
                        newExp.Payments.Add(new BusinessExpencePayment
                        {
                            Amount = p.Amount,
                            PaymentAccountId = p.PaymentAccountId,
                            Date = p.Date ?? billDate
                        });
                    }
                    _context.BusinessExpences.Add(newExp);
                }
            }

            await _context.SaveChangesAsync();
        }

        private sealed class BuyingBillExpenceSyncDto
        {
            public int? Id { get; set; }
            public string ExpenceType { get; set; } = string.Empty;
            public decimal TotalAmount { get; set; }
            public List<BuyingBillExpencePaymentDto> Payments { get; set; } = new();
        }
    }
}
