using AutoMapper;
using Microsoft.EntityFrameworkCore;
using RF.WebApi.Api.Apis.Authentication;
using RF.WebApi.Api.Application.DTOs.SellingBill;
using RF.WebApi.Api.Domain.Common;
using RF.WebApi.Api.Domain.Exceptions;
using RF.WebApi.Api.Domain.Interfaces;
using RF.WebApi.Api.Infrastructure.Data.Tables;
using RF.WebApi.Infrastructure.Data.DataBase;


namespace RF.WebApi.Api.Infrastructure.Services
{
    public class SellingBillService : ISellingBillService
    {
        private readonly RFDBContext _context;
        private readonly IMapper _mapper;
        private readonly IBusinessYearService _businessYearService;
        private readonly IPdfService _pdfService;
        private readonly IWhatsAppIntegrationService _whatsAppIntegrationService;
        private readonly IEmailIntegrationService _emailIntegrationService;

        public SellingBillService(RFDBContext context, IMapper mapper, IBusinessYearService businessYearService, IPdfService pdfService, IWhatsAppIntegrationService whatsAppIntegrationService, IEmailIntegrationService emailIntegrationService)
        {
            _context = context;
            _mapper = mapper;
            _businessYearService = businessYearService;
            _pdfService = pdfService;
            _whatsAppIntegrationService = whatsAppIntegrationService;
            _emailIntegrationService = emailIntegrationService;
        }

        public async Task<ServiceResponse<int>> CreateSellingBill(CreateSellingBillDto dto)
        {
            return await ServiceResponse<int>.Execute(async err =>
            {
                var bill = _mapper.Map<SellingBill>(dto);
                bill.AccountId = Token.AccountId;
                
                bool isAutogeneratedNeeded = string.IsNullOrWhiteSpace(bill.BillNo);
                if (isAutogeneratedNeeded)
                {
                    bill.BillNo = "TEMP_BILL_NO"; // Fallback to auto-generation after save
                }

                _context.SellingBills.Add(bill);

                foreach (var payment in bill.Payments)
                {
                    payment.Bill = bill;
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();

                // Autogenerate BillNo with ID
                if (bill.BillNo == "TEMP_BILL_NO")
                {
                    var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == Token.AccountId);
                    string initials = "ABC";
                    if (account != null && !string.IsNullOrWhiteSpace(account.ProfileName))
                    {
                        var words = account.ProfileName.Split(' ', StringSplitOptions.RemoveEmptyEntries);
                        if (words.Length > 0)
                        {
                            initials = string.Join("", words.Select(w => w[0])).ToUpper();
                        }
                    }
                    
                    string year = bill.Date.HasValue ? bill.Date.Value.Year.ToString() : DateTime.Now.Year.ToString();
                    bill.BillNo = $"{initials}{year}SB{bill.Id}";
                    await _context.SaveChangesAsync();
                }

                return bill.Id ?? default;
            });
        }

        public Task<ServiceResponse<SellingBillDto>> GetSellingBillById(int id)
        {
            return ServiceResponse<SellingBillDto>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Payments)
                    .Include(b => b.Items)
                        .ThenInclude(i => i.Product)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return default;
                }

                return _mapper.Map<SellingBillDto>(bill);
            });
        }

        public Task<ServiceResponse<bool>> UpdateSellingBill(UpdateSellingBillDto dto)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Payments)
                    .Include(b => b.Items)
                        .ThenInclude(i => i.Product)
                    .FirstOrDefaultAsync(b => b.Id == dto.Id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return false;
                }

                // Sync scalar properties (Items, Payments are ignored in Profile)
                _mapper.Map(dto, bill);
                
                // Generic helper handles Add, Update, and Remove for collections safely
                _context.SyncCollection(bill.Items, dto.Items, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);
                _context.SyncCollection(bill.Payments, dto.Payments, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);

                foreach (var payment in bill.Payments)
                {
                    payment.Bill = bill;
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();
                return true;
            });
        }

        public Task<ServiceResponse<bool>> DeleteSellingBill(int id)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                     .Include(b => b.Payments)
                     .Include(b => b.Items)
                     .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return false;
                }

                _context.SellingBillItems.RemoveRange(bill.Items);
                _context.SellingBillPayments.RemoveRange(bill.Payments);
                _context.SellingBills.Remove(bill);

                await _context.SaveChangesAsync();
                return true;
            });
        }

        public Task<ServiceResponse<List<SellingBillListDto>>> GetAllSellingBills()
        {
            return ServiceResponse<List<SellingBillListDto>>.Execute(async err =>
            {
                var accountId = Token.AccountId;

                var dateRangeResponse = await _businessYearService.GetSelectedBusinessYearDates();
                if (!dateRangeResponse.Success)
                {
                    err.SetErrors(dateRangeResponse);
                    return default;
                }

                var (startDate, endDate) = dateRangeResponse.Data;

                var bills = await _context.SellingBills
                    .Include(b => b.Payments)
                    .Include(b => b.Items)
                    .Where(b => b.AccountId == accountId && b.Date >= startDate && b.Date <= endDate)
                    .OrderByDescending(b => b.Date)
                    .AsNoTracking()
                    .ToListAsync();

                return _mapper.Map<List<SellingBillListDto>>(bills);
            });
        }

        public Task<ServiceResponse<byte[]>> GenerateInvoicePdf(int id)
        {
            return ServiceResponse<byte[]>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Items)
                        .ThenInclude(i => i.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return default;
                }

                var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == Token.AccountId);
                if (account == null)
                {
                    err.AddError("Account not found");
                    return default;
                }

                return await _pdfService.GenerateSellingBillPdf(bill, account);
            });
        }

        public Task<ServiceResponse<bool>> SendWhatsAppMessage(int id)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Items)
                        .ThenInclude(i => i.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return false;
                }

                var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == Token.AccountId);
                if (account == null)
                {
                    err.AddError("Account not found");
                    return false;
                }

                if (!account.EnableAdvancedWhatsApp)
                {
                    err.AddError("Advanced WhatsApp is not enabled for this account.");
                    return false;
                }

                var result = await _whatsAppIntegrationService.SendBillAsync(bill, account);
                if (!result.Success)
                {
                    err.SetErrors(result);
                    return false;
                }

                return true;
            });
        }

        public Task<ServiceResponse<bool>> SendEmailMessage(int id)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Items)
                        .ThenInclude(i => i.Product)
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == id && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return false;
                }

                var account = await _context.Accounts.FirstOrDefaultAsync(a => a.Id == Token.AccountId);
                if (account == null)
                {
                    err.AddError("Account not found");
                    return false;
                }

                var result = await _emailIntegrationService.SendBillAsync(bill, account);
                if (!result.Success)
                {
                    err.SetErrors(result);
                    return false;
                }

                return true;
            });
        }

        public Task<ServiceResponse<bool>> UpdatePayments(int billId, List<SellingBillPaymentDto> payments)
        {
            return ServiceResponse<bool>.Execute(async err =>
            {
                var bill = await _context.SellingBills
                    .Include(b => b.Payments)
                    .FirstOrDefaultAsync(b => b.Id == billId && b.AccountId == Token.AccountId);

                if (bill == null)
                {
                    err.AddError(SellingBillMessages.NotFound);
                    return false;
                }

                _context.SyncCollection(bill.Payments, payments, (e, d) => d.Id > 0 && e.Id == d.Id, _mapper);

                foreach (var payment in bill.Payments)
                {
                    payment.Bill = bill;
                    if (payment.Date == null) payment.Date = bill.Date;
                }

                await _context.SaveChangesAsync();
                return true;
            });
        }
    }
}
