// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RF.WebApi.Infrastructure.Data.DataBase;

#nullable disable

namespace RF.WebApi.Api.Migrations
{
    [DbContext(typeof(RFDBContext))]
    [Migration("20260509113545_090520264")]
    partial class _090520264
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Account", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("INR");

                    b.Property<string>("DateFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailSmtpEnableSsl")
                        .HasColumnType("bit");

                    b.Property<string>("EmailSmtpHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSmtpPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmailSmtpPort")
                        .HasColumnType("int");

                    b.Property<string>("EmailSmtpUsername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EnableAdvancedWhatsApp")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableEmail")
                        .HasColumnType("bit");

                    b.Property<bool>("EnableSuggestions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableVoiceTyping")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("EnableWhatsApp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("GSTIN")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProfileLogoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ShortDateFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("WhatsAppAccessToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppBusinessId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatsAppNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PersonOccupation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountPerson", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AccountPersonId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("AddContribution", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContributionPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AddContributionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddContributionId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("AddContributionPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Agency", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AgencyPerson", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AgencyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PersonOccupation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("AgencyPerson", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BuyingBillId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("ExpenceType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal?>("TotalAmount")
                        .IsRequired()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BuyingBillId");

                    b.ToTable("BusinessExpence", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpencePayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BusinessExpenceId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessExpenceId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("BusinessExpencePayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("date");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("BusinessYear", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AgencyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AgencyId");

                    b.ToTable("BuyingBill", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BuyingBillItem", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("BuyingBillPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Entity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("Entity", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayName = "User Role",
                            EntityName = "UserRole"
                        },
                        new
                        {
                            Id = 2,
                            DisplayName = "Currency",
                            EntityName = "Currency"
                        });
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AccountPersonId")
                        .HasColumnType("int");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("PaymentAccount", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RelatedEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("EntityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("RelatedDisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RelatedEntityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("RelatedEntity", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EntityId = 1,
                            RelatedDisplayName = "Super Admin",
                            RelatedEntityName = "SuperAdmin"
                        },
                        new
                        {
                            Id = 2,
                            EntityId = 1,
                            RelatedDisplayName = "Admin",
                            RelatedEntityName = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            EntityId = 2,
                            RelatedDisplayName = "INR (₹)",
                            RelatedEntityName = "en-IN"
                        },
                        new
                        {
                            Id = 4,
                            EntityId = 2,
                            RelatedDisplayName = "USD ($)",
                            RelatedEntityName = "en-US"
                        },
                        new
                        {
                            Id = 5,
                            EntityId = 2,
                            RelatedDisplayName = "GBP (£)",
                            RelatedEntityName = "en-GB"
                        },
                        new
                        {
                            Id = 6,
                            EntityId = 2,
                            RelatedDisplayName = "EUR (€)",
                            RelatedEntityName = "en-IE"
                        });
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AccountPersonId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("RemoveContribution", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContributionPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RemoveContributionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentAccountId");

                    b.HasIndex("RemoveContributionId");

                    b.ToTable("RemoveContributionPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SellingBill", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("SellingBillItem", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .HasColumnType("date");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("SellingBillPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ItemId")
                        .IsUnique();

                    b.ToTable("SellingItemWarrenty", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SystemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("PropertyDisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PropertyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PropertyValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SystemConfiguration", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PropertyDisplayName = "Enable Account Deletion",
                            PropertyName = "EnableDeleteAccount",
                            PropertyType = "boolean",
                            PropertyValue = "false"
                        },
                        new
                        {
                            Id = 2,
                            PropertyDisplayName = "Table Scroll Height",
                            PropertyName = "TableScrollHeight",
                            PropertyType = "string",
                            PropertyValue = "65vh"
                        });
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "hiteshkumar252020@gmail.com",
                            FirstName = "System",
                            IsActive = false,
                            Password = "$2a$11$LRY4mjvdqRX5d8RYQxqJcO/aKWnmMzgrLbKmEX1/g02H5v0.7QJhC",
                            Role = "SuperAdmin",
                            Surname = "User"
                        });
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.UserSelectedYearMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessYearId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessYearId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSelectedYearMapping", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", "AccountPerson")
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountPerson");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContributionPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", "AddContribution")
                        .WithMany("Payments")
                        .HasForeignKey("AddContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AddContribution");

                    b.Navigation("PaymentAccount");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AgencyPerson", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", "BuyingBill")
                        .WithMany("Expences")
                        .HasForeignKey("BuyingBillId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BuyingBill");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpencePayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", "BusinessExpence")
                        .WithMany("Payments")
                        .HasForeignKey("BusinessExpenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessExpence");

                    b.Navigation("PaymentAccount");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillItem", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("PaymentAccount");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", null)
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RelatedEntity", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Entity", "Entity")
                        .WithMany("RelatedEntities")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entity");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", "AccountPerson")
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AccountPerson");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContributionPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", "RemoveContribution")
                        .WithMany("Payments")
                        .HasForeignKey("RemoveContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentAccount");

                    b.Navigation("RemoveContribution");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", null)
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", "Bill")
                        .WithMany("Payments")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", "PaymentAccount")
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("PaymentAccount");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", "Bill")
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", "Item")
                        .WithOne("Warrenty")
                        .HasForeignKey("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", "ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.User", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Account");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.UserSelectedYearMapping", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", null)
                        .WithMany()
                        .HasForeignKey("BusinessYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.Navigation("Expences");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Entity", b =>
                {
                    b.Navigation("RelatedEntities");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", b =>
                {
                    b.Navigation("Warrenty");
                });
#pragma warning restore 612, 618
        }
    }
}
