// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RF.WebApi.Infrastructure.Data.DataBase;

#nullable disable

namespace RF.WebApi.Api.Migrations
{
    [DbContext(typeof(RFDBContext))]
    partial class RFDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Account", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("CurrencyType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("INR");

                    b.Property<string>("ProfileLogoLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PersonOccupation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("AccountPerson", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountPersonId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("AddContribution", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContributionPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AddContributionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddContributionId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("AddContributionPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Agency", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AgencyPerson", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("AgencyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PersonOccupation")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgencyId");

                    b.ToTable("AgencyPerson", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("ExpenceType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("BusinessExpence", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpencePayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BusinessExpenceId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BusinessExpenceId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("BusinessExpencePayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("date");

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("BusinessYear", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AgencyId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AgencyId");

                    b.ToTable("BuyingBill", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillExpence", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BuyingBillId")
                        .HasColumnType("int");

                    b.Property<string>("ExpenceType")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BuyingBillId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("BuyingBillExpence", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BuyingBillId")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quntity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BuyingBillId");

                    b.ToTable("BuyingBillItem", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("BuyingBillId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("BuyingBillId");

                    b.HasIndex("PaymentAccountId");

                    b.ToTable("BuyingBillPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Entity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("DisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EntityName")
                        .IsUnique();

                    b.ToTable("Entity", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("AccountPersonId")
                        .HasColumnType("int");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("PaymentAccount", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RelatedEntity", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("EntityId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("RelatedDisplayName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RelatedEntityName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("RelatedEntity", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountPersonId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AccountPersonId");

                    b.ToTable("RemoveContribution", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContributionPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RemoveContributionId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PaymentAccountId");

                    b.HasIndex("RemoveContributionId");

                    b.ToTable("RemoveContributionPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillNo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<decimal?>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Email")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("PhoneNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("SellingBill", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Quntity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("WarrentyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("WarrentyId");

                    b.ToTable("SellingBillItem", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillPayment", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<decimal?>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("PaymentAccountId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SellingBillId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("PaymentAccountId");

                    b.HasIndex("SellingBillId");

                    b.ToTable("SellingBillPayment", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("BillId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<int?>("ItemId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("Month")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.HasIndex("ItemId");

                    b.ToTable("SellingItemWarrenty", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.User", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AccountId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Email = "hiteshkumar252020@gmail.com",
                            FirstName = "System",
                            IsActive = false,
                            Password = "$2a$11$Bch1OGu5MzXe5wFkC9tzgerad4qMd/gvMBE1f60Il4c3/Tyb/fNoi",
                            Role = "SuperAdmin",
                            Surname = "User"
                        });
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.UserSelectedYearMapping", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<int>("BusinessYearId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("BusinessYearId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSelectedYearMapping", (string)null);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", null)
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AddContributionPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AddContribution", null)
                        .WithMany()
                        .HasForeignKey("AddContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.AgencyPerson", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", null)
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpencePayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", null)
                        .WithMany("Payments")
                        .HasForeignKey("BusinessExpenceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Agency", "Agency")
                        .WithMany()
                        .HasForeignKey("AgencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agency");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillExpence", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany("Expences")
                        .HasForeignKey("BuyingBillId");

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillItem", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany("Items")
                        .HasForeignKey("BuyingBillId");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBillPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", null)
                        .WithMany("Payments")
                        .HasForeignKey("BuyingBillId");

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", null)
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RelatedEntity", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Entity", null)
                        .WithMany()
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.AccountPerson", null)
                        .WithMany()
                        .HasForeignKey("AccountPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContributionPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.RemoveContribution", null)
                        .WithMany()
                        .HasForeignKey("RemoveContributionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", null)
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", "Warrenty")
                        .WithMany()
                        .HasForeignKey("WarrentyId");

                    b.Navigation("Warrenty");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillPayment", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.PaymentAccount", null)
                        .WithMany()
                        .HasForeignKey("PaymentAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", null)
                        .WithMany("Payments")
                        .HasForeignKey("SellingBillId");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingItemWarrenty", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", null)
                        .WithMany()
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBillItem", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.User", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.UserSelectedYearMapping", b =>
                {
                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessYear", null)
                        .WithMany()
                        .HasForeignKey("BusinessYearId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("RF.WebApi.Api.Infrastructure.Data.Tables.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BusinessExpence", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.BuyingBill", b =>
                {
                    b.Navigation("Expences");

                    b.Navigation("Items");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("RF.WebApi.Api.Infrastructure.Data.Tables.SellingBill", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
